### ISSUE TITLE
DEAP_1D.py, DEAP_1D_3D.py are inaccessible

### ISSUE THREAD

**Issue by STDECG** [dolphin-in-a-coma/multi-task-cnn-eeg-emotion#1]
Hello author, the Slides Video Colab Paper etc you mentioned need to go to https://cntr.click/a1m7LNa etc, but I got the error cntr.click and the connection was accidentally terminated. I am interested in your work and would like your help.

**Comment by dolphin-in-a-coma** [comment]
Hi! Thanks for noticing. Fixed it.
https://github.com/dolphin-in-a-coma/multi-task-cnn-eeg-emotion/commit/94157974a4b700d97b846a8505726a9052743033
